BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `uptime` (
	`pid`	TEXT NOT NULL,
	`uptime_in_sec`	REAL NOT NULL,
	`idle_in_sec`	REAL NOT NULL,
	`timestamp`	DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `projects` (
	`pid`	TEXT NOT NULL,
	`title`	INTEGER NOT NULL,
	`metapackage`	TEXT NOT NULL,
	`timestamp`	DATETIME DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
